import type {
  AssertionId,
  DistrictId,
  JurisdictionId,
  JurisdictionRegistrySnapshot,
  OfficeId,
  PublicBodyId,
  RegistryAttribution,
} from './jurisdiction-registry.js';

const START = '2020-01-01T00:00:00.000Z';
const CHANGE = '2026-01-01T00:00:00.000Z';
const FUTURE = '2027-01-01T00:00:00.000Z';
const SHA_A = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const SHA_B = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';

const jid = (value: string) => value as JurisdictionId;
const did = (value: string) => value as DistrictId;
const bid = (value: string) => value as PublicBodyId;
const oid = (value: string) => value as OfficeId;

function attribution(
  id: string,
  overrides: Partial<RegistryAttribution> = {},
): RegistryAttribution {
  return {
    assertionId: id as AssertionId,
    conflict: 'clear',
    coverage: 'supported',
    freshness: 'current',
    observedAt: '2026-08-06T12:00:00.000Z',
    sourceReference: `synthetic://registry/${id}`,
    supersedesAssertionId: null,
    ...overrides,
  };
}

export const SYNTHETIC_JURISDICTION_REGISTRY = Object.freeze({
  schemaVersion: 'jurisdiction-registry.v1',
  dataMode: 'synthetic',
  generatedAt: '2026-08-06T12:00:00.000Z',
  jurisdictions: [
    {
      jurisdictionId: jid('jurisdiction:ca'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca',
          name: 'Canada synthetic fixture',
          slug: 'canada-synthetic',
          kind: 'country',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:ca'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:ca:maple'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca:maple',
          name: 'Maple Province',
          slug: 'maple-province',
          kind: 'province',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:ca:maple'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:ca:north-region'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca:north-region',
          name: 'North Regional District',
          slug: 'north-regional-district',
          kind: 'regional_district',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:ca:north-region'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:ca:harbour'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca:harbour:old-name',
          name: 'Harbour Village',
          slug: 'harbour-village',
          kind: 'municipality',
          status: 'former',
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:jv:ca:harbour:old'),
        },
        {
          versionId: 'jv:ca:harbour:current-name',
          name: 'Harbour City',
          slug: 'harbour-city',
          kind: 'municipality',
          status: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:jv:ca:harbour:new', {
            supersedesAssertionId: 'assertion:jv:ca:harbour:old' as AssertionId,
          }),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:ca:old-bay'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca:old-bay',
          name: 'Old Bay Municipality',
          slug: 'old-bay',
          kind: 'municipality',
          status: 'amalgamated',
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:jv:ca:old-bay'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:ca:new-bay'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'jv:ca:new-bay',
          name: 'New Bay Municipality',
          slug: 'new-bay',
          kind: 'municipality',
          status: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:jv:ca:new-bay'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us',
          name: 'United States synthetic fixture',
          slug: 'united-states-synthetic',
          kind: 'country',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us:example-state'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us:example-state',
          name: 'Example State',
          slug: 'example-state',
          kind: 'state',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us:example-state'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us:example-county'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us:example-county',
          name: 'Example County',
          slug: 'example-county',
          kind: 'county',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us:example-county'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us:example-city'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us:example-city',
          name: 'Example City',
          slug: 'example-city',
          kind: 'municipality',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us:example-city'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us:unincorporated'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us:unincorporated',
          name: 'Example Unincorporated Area',
          slug: 'example-unincorporated',
          kind: 'unincorporated_area',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us:unincorporated'),
        },
      ],
    },
    {
      jurisdictionId: jid('jurisdiction:us:water'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'jv:us:water',
          name: 'Example Water District',
          slug: 'example-water-district',
          kind: 'special_district',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:jv:us:water', { coverage: 'partial' }),
        },
      ],
    },
  ],
  jurisdictionRelationships: [
    {
      relationshipId: 'jr:ca:maple-country',
      subjectJurisdictionId: jid('jurisdiction:ca:maple'),
      objectJurisdictionId: jid('jurisdiction:ca'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:maple-country'),
    },
    {
      relationshipId: 'jr:ca:region-province',
      subjectJurisdictionId: jid('jurisdiction:ca:north-region'),
      objectJurisdictionId: jid('jurisdiction:ca:maple'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:region-province'),
    },
    {
      relationshipId: 'jr:ca:harbour-province',
      subjectJurisdictionId: jid('jurisdiction:ca:harbour'),
      objectJurisdictionId: jid('jurisdiction:ca:maple'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:harbour-province'),
    },
    {
      relationshipId: 'jr:ca:harbour-region',
      subjectJurisdictionId: jid('jurisdiction:ca:harbour'),
      objectJurisdictionId: jid('jurisdiction:ca:north-region'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:harbour-region'),
    },
    {
      relationshipId: 'jr:ca:old-bay-region',
      subjectJurisdictionId: jid('jurisdiction:ca:old-bay'),
      objectJurisdictionId: jid('jurisdiction:ca:north-region'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: CHANGE,
      attribution: attribution('assertion:jr:ca:old-bay-region'),
    },
    {
      relationshipId: 'jr:ca:new-bay-region',
      subjectJurisdictionId: jid('jurisdiction:ca:new-bay'),
      objectJurisdictionId: jid('jurisdiction:ca:north-region'),
      kind: 'contained_by',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:new-bay-region'),
    },
    {
      relationshipId: 'jr:ca:new-bay-successor',
      subjectJurisdictionId: jid('jurisdiction:ca:new-bay'),
      objectJurisdictionId: jid('jurisdiction:ca:old-bay'),
      kind: 'successor_of',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:jr:ca:new-bay-successor'),
    },
    {
      relationshipId: 'jr:us:state-country',
      subjectJurisdictionId: jid('jurisdiction:us:example-state'),
      objectJurisdictionId: jid('jurisdiction:us'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:state-country'),
    },
    {
      relationshipId: 'jr:us:county-state',
      subjectJurisdictionId: jid('jurisdiction:us:example-county'),
      objectJurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:county-state'),
    },
    {
      relationshipId: 'jr:us:city-county',
      subjectJurisdictionId: jid('jurisdiction:us:example-city'),
      objectJurisdictionId: jid('jurisdiction:us:example-county'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:city-county'),
    },
    {
      relationshipId: 'jr:us:city-state',
      subjectJurisdictionId: jid('jurisdiction:us:example-city'),
      objectJurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:city-state'),
    },
    {
      relationshipId: 'jr:us:unincorporated-county',
      subjectJurisdictionId: jid('jurisdiction:us:unincorporated'),
      objectJurisdictionId: jid('jurisdiction:us:example-county'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:unincorporated-county'),
    },
    {
      relationshipId: 'jr:us:water-state',
      subjectJurisdictionId: jid('jurisdiction:us:water'),
      objectJurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:water-state'),
    },
    {
      relationshipId: 'jr:us:water-city',
      subjectJurisdictionId: jid('jurisdiction:us:water'),
      objectJurisdictionId: jid('jurisdiction:us:example-city'),
      kind: 'overlaps',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:water-city', {
        conflict: 'conflicting',
        coverage: 'partial',
      }),
    },
    {
      relationshipId: 'jr:us:water-unincorporated',
      subjectJurisdictionId: jid('jurisdiction:us:water'),
      objectJurisdictionId: jid('jurisdiction:us:unincorporated'),
      kind: 'overlaps',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:jr:us:water-unincorporated', { coverage: 'partial' }),
    },
  ],
  districts: [
    {
      districtId: did('district:ca:maple-federal-old'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'dv:ca:maple-federal-old',
          name: 'Maple Federal District 2015',
          slug: 'maple-federal-2015',
          kind: 'federal_electoral',
          status: 'former',
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:dv:ca:maple-federal-old'),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:ca:maple-federal-old',
          geometryReference: 'synthetic://geometry/ca/maple-federal-old.geojson',
          geometrySha256: SHA_A,
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:boundary:ca:maple-federal-old'),
        },
      ],
    },
    {
      districtId: did('district:ca:maple-federal-new'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'dv:ca:maple-federal-new',
          name: 'Maple Federal District 2026',
          slug: 'maple-federal-2026',
          kind: 'federal_electoral',
          status: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:dv:ca:maple-federal-new'),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:ca:maple-federal-new',
          geometryReference: 'synthetic://geometry/ca/maple-federal-new.geojson',
          geometrySha256: SHA_B,
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:ca:maple-federal-new'),
        },
      ],
    },
    {
      districtId: did('district:ca:maple-provincial'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'dv:ca:maple-provincial:old',
          name: 'Harbour Provincial District',
          slug: 'harbour-provincial',
          kind: 'provincial_electoral',
          status: 'former',
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:dv:ca:maple-provincial:old'),
        },
        {
          versionId: 'dv:ca:maple-provincial:new',
          name: 'Harbour Coast Provincial District',
          slug: 'harbour-coast-provincial',
          kind: 'provincial_electoral',
          status: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:dv:ca:maple-provincial:new', {
            supersedesAssertionId: 'assertion:dv:ca:maple-provincial:old' as AssertionId,
          }),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:ca:maple-provincial:old',
          geometryReference: 'synthetic://geometry/ca/maple-provincial-old.geojson',
          geometrySha256: SHA_A,
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:boundary:ca:maple-provincial:old'),
        },
        {
          boundaryVersionId: 'boundary:ca:maple-provincial:new',
          geometryReference: 'synthetic://geometry/ca/maple-provincial-new.geojson',
          geometrySha256: SHA_B,
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:ca:maple-provincial:new'),
        },
      ],
    },
    {
      districtId: did('district:us:congressional'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'dv:us:congressional',
          name: 'Example Congressional District',
          slug: 'example-congressional',
          kind: 'federal_electoral',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:dv:us:congressional'),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:us:congressional',
          geometryReference: 'synthetic://geometry/us/congressional.geojson',
          geometrySha256: SHA_A,
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:us:congressional'),
        },
      ],
    },
    {
      districtId: did('district:us:state-senate'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'dv:us:state-senate',
          name: 'Example State Senate District',
          slug: 'example-state-senate',
          kind: 'state_legislative',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:dv:us:state-senate'),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:us:state-senate',
          geometryReference: 'synthetic://geometry/us/state-senate.geojson',
          geometrySha256: SHA_B,
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:us:state-senate'),
        },
      ],
    },
    {
      districtId: did('district:us:city-ward'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'dv:us:city-ward',
          name: 'Example City Ward',
          slug: 'example-city-ward',
          kind: 'local_electoral',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:dv:us:city-ward'),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:us:city-ward',
          geometryReference: 'synthetic://geometry/us/city-ward.geojson',
          geometrySha256: SHA_A,
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:us:city-ward'),
        },
      ],
    },
    {
      districtId: did('district:us:water'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'dv:us:water',
          name: 'Example Water Service District',
          slug: 'example-water-service',
          kind: 'special',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:dv:us:water', { coverage: 'partial' }),
        },
      ],
      boundaries: [
        {
          boundaryVersionId: 'boundary:us:water',
          geometryReference: 'synthetic://geometry/us/water.geojson',
          geometrySha256: SHA_B,
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:boundary:us:water', {
            freshness: 'unknown',
            coverage: 'partial',
          }),
        },
      ],
    },
  ],
  districtJurisdictionRelationships: [
    {
      relationshipId: 'djr:ca:fed-old-province',
      districtId: did('district:ca:maple-federal-old'),
      jurisdictionId: jid('jurisdiction:ca:maple'),
      kind: 'represents',
      effectiveFrom: START,
      effectiveTo: CHANGE,
      attribution: attribution('assertion:djr:ca:fed-old-province'),
    },
    {
      relationshipId: 'djr:ca:fed-new-province',
      districtId: did('district:ca:maple-federal-new'),
      jurisdictionId: jid('jurisdiction:ca:maple'),
      kind: 'represents',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:djr:ca:fed-new-province'),
    },
    {
      relationshipId: 'djr:ca:prov-harbour',
      districtId: did('district:ca:maple-provincial'),
      jurisdictionId: jid('jurisdiction:ca:harbour'),
      kind: 'overlaps',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:djr:ca:prov-harbour'),
    },
    {
      relationshipId: 'djr:us:congress-state',
      districtId: did('district:us:congressional'),
      jurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'represents',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:djr:us:congress-state'),
    },
    {
      relationshipId: 'djr:us:senate-state',
      districtId: did('district:us:state-senate'),
      jurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'represents',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:djr:us:senate-state'),
    },
    {
      relationshipId: 'djr:us:ward-city',
      districtId: did('district:us:city-ward'),
      jurisdictionId: jid('jurisdiction:us:example-city'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:djr:us:ward-city'),
    },
    {
      relationshipId: 'djr:us:water-special',
      districtId: did('district:us:water'),
      jurisdictionId: jid('jurisdiction:us:water'),
      kind: 'contained_by',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:djr:us:water-special', { coverage: 'partial' }),
    },
  ],
  districtLineage: [
    {
      lineageId: 'lineage:ca:maple-federal-2026',
      districtId: did('district:ca:maple-federal-new'),
      predecessorDistrictId: did('district:ca:maple-federal-old'),
      kind: 'redistricted_from',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:lineage:ca:maple-federal-2026'),
    },
  ],
  publicBodies: [
    {
      publicBodyId: bid('body:ca:maple-legislature'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'bv:ca:maple-legislature',
          name: 'Maple Legislative Assembly',
          slug: 'maple-legislative-assembly',
          kind: 'legislature',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:bv:ca:maple-legislature'),
        },
      ],
    },
    {
      publicBodyId: bid('body:ca:north-board'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'bv:ca:north-board',
          name: 'North Regional Board',
          slug: 'north-regional-board',
          kind: 'board',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:bv:ca:north-board'),
        },
      ],
    },
    {
      publicBodyId: bid('body:ca:harbour-council'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'bv:ca:harbour-council',
          name: 'Harbour City Council',
          slug: 'harbour-city-council',
          kind: 'council',
          status: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:bv:ca:harbour-council'),
        },
      ],
    },
    {
      publicBodyId: bid('body:us:state-legislature'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'bv:us:state-legislature',
          name: 'Example State Legislature',
          slug: 'example-state-legislature',
          kind: 'legislature',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:bv:us:state-legislature'),
        },
      ],
    },
    {
      publicBodyId: bid('body:us:county-board'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'bv:us:county-board',
          name: 'Example County Board',
          slug: 'example-county-board',
          kind: 'board',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:bv:us:county-board'),
        },
      ],
    },
    {
      publicBodyId: bid('body:us:water-board'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'bv:us:water-board',
          name: 'Example Water Board',
          slug: 'example-water-board',
          kind: 'board',
          status: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:bv:us:water-board', { coverage: 'partial' }),
        },
      ],
    },
  ],
  bodyJurisdictionRelationships: [
    {
      relationshipId: 'bjr:ca:legislature-province',
      publicBodyId: bid('body:ca:maple-legislature'),
      jurisdictionId: jid('jurisdiction:ca:maple'),
      kind: 'governs',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:ca:legislature-province'),
    },
    {
      relationshipId: 'bjr:ca:board-region',
      publicBodyId: bid('body:ca:north-board'),
      jurisdictionId: jid('jurisdiction:ca:north-region'),
      kind: 'governs',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:ca:board-region'),
    },
    {
      relationshipId: 'bjr:ca:council-harbour',
      publicBodyId: bid('body:ca:harbour-council'),
      jurisdictionId: jid('jurisdiction:ca:harbour'),
      kind: 'governs',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:ca:council-harbour'),
    },
    {
      relationshipId: 'bjr:us:legislature-state',
      publicBodyId: bid('body:us:state-legislature'),
      jurisdictionId: jid('jurisdiction:us:example-state'),
      kind: 'governs',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:us:legislature-state'),
    },
    {
      relationshipId: 'bjr:us:board-county',
      publicBodyId: bid('body:us:county-board'),
      jurisdictionId: jid('jurisdiction:us:example-county'),
      kind: 'governs',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:us:board-county'),
    },
    {
      relationshipId: 'bjr:us:water-special',
      publicBodyId: bid('body:us:water-board'),
      jurisdictionId: jid('jurisdiction:us:water'),
      kind: 'governs',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:bjr:us:water-special', { coverage: 'partial' }),
    },
  ],
  offices: [
    {
      officeId: oid('office:ca:maple-member'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'ov:ca:maple-member',
          publicBodyId: bid('body:ca:maple-legislature'),
          districtId: did('district:ca:maple-provincial'),
          name: 'Member of the Maple Legislative Assembly',
          slug: 'maple-assembly-member',
          selectionMethod: 'elected',
          operationalState: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:ov:ca:maple-member'),
        },
      ],
    },
    {
      officeId: oid('office:ca:north-director'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'ov:ca:north-director',
          publicBodyId: bid('body:ca:north-board'),
          districtId: null,
          name: 'Appointed Regional Director',
          slug: 'appointed-regional-director',
          selectionMethod: 'appointed',
          operationalState: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:ov:ca:north-director'),
        },
      ],
    },
    {
      officeId: oid('office:ca:harbour-mayor'),
      countryCode: 'CA',
      versions: [
        {
          versionId: 'ov:ca:harbour-mayor:active',
          publicBodyId: bid('body:ca:harbour-council'),
          districtId: null,
          name: 'Mayor of Harbour City',
          slug: 'harbour-city-mayor',
          selectionMethod: 'elected',
          operationalState: 'active',
          effectiveFrom: CHANGE,
          effectiveTo: FUTURE,
          attribution: attribution('assertion:ov:ca:harbour-mayor:active'),
        },
        {
          versionId: 'ov:ca:harbour-mayor:vacant',
          publicBodyId: bid('body:ca:harbour-council'),
          districtId: null,
          name: 'Mayor of Harbour City',
          slug: 'harbour-city-mayor',
          selectionMethod: 'elected',
          operationalState: 'vacant',
          effectiveFrom: FUTURE,
          effectiveTo: null,
          attribution: attribution('assertion:ov:ca:harbour-mayor:vacant', {
            supersedesAssertionId: 'assertion:ov:ca:harbour-mayor:active' as AssertionId,
          }),
        },
      ],
    },
    {
      officeId: oid('office:us:state-senator'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'ov:us:state-senator',
          publicBodyId: bid('body:us:state-legislature'),
          districtId: did('district:us:state-senate'),
          name: 'Example State Senator',
          slug: 'example-state-senator',
          selectionMethod: 'elected',
          operationalState: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:ov:us:state-senator'),
        },
      ],
    },
    {
      officeId: oid('office:us:county-commissioner'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'ov:us:county-commissioner',
          publicBodyId: bid('body:us:county-board'),
          districtId: null,
          name: 'Example County Commissioner',
          slug: 'example-county-commissioner',
          selectionMethod: 'elected',
          operationalState: 'active',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:ov:us:county-commissioner'),
        },
      ],
    },
    {
      officeId: oid('office:us:water-director'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'ov:us:water-director',
          publicBodyId: bid('body:us:water-board'),
          districtId: did('district:us:water'),
          name: 'Appointed Water Director',
          slug: 'appointed-water-director',
          selectionMethod: 'appointed',
          operationalState: 'acting',
          effectiveFrom: START,
          effectiveTo: null,
          attribution: attribution('assertion:ov:us:water-director', { coverage: 'partial' }),
        },
      ],
    },
    {
      officeId: oid('office:us:former-commissioner'),
      countryCode: 'US',
      versions: [
        {
          versionId: 'ov:us:former-commissioner:active',
          publicBodyId: bid('body:us:county-board'),
          districtId: null,
          name: 'Former At-Large Commissioner',
          slug: 'former-at-large-commissioner',
          selectionMethod: 'elected',
          operationalState: 'active',
          effectiveFrom: START,
          effectiveTo: CHANGE,
          attribution: attribution('assertion:ov:us:former-commissioner:active'),
        },
        {
          versionId: 'ov:us:former-commissioner:abolished',
          publicBodyId: bid('body:us:county-board'),
          districtId: null,
          name: 'Former At-Large Commissioner',
          slug: 'former-at-large-commissioner',
          selectionMethod: 'elected',
          operationalState: 'abolished',
          effectiveFrom: CHANGE,
          effectiveTo: null,
          attribution: attribution('assertion:ov:us:former-commissioner:abolished', {
            supersedesAssertionId: 'assertion:ov:us:former-commissioner:active' as AssertionId,
          }),
        },
      ],
    },
  ],
  externalIdentifiers: [
    {
      externalIdentifierId: 'external:ca:harbour:old',
      entityKind: 'jurisdiction',
      entityId: jid('jurisdiction:ca:harbour'),
      issuer: 'synthetic-ca-municipal-registry',
      identifier: 'HARBOUR-VILLAGE-001',
      effectiveFrom: START,
      effectiveTo: CHANGE,
      attribution: attribution('assertion:external:ca:harbour:old'),
    },
    {
      externalIdentifierId: 'external:ca:harbour:new',
      entityKind: 'jurisdiction',
      entityId: jid('jurisdiction:ca:harbour'),
      issuer: 'synthetic-ca-municipal-registry',
      identifier: 'HARBOUR-CITY-019',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:external:ca:harbour:new', {
        supersedesAssertionId: 'assertion:external:ca:harbour:old' as AssertionId,
      }),
    },
    {
      externalIdentifierId: 'external:ca:provincial:old',
      entityKind: 'district',
      entityId: did('district:ca:maple-provincial'),
      issuer: 'synthetic-ca-election-authority',
      identifier: 'MAPLE-PROV-OLD',
      effectiveFrom: START,
      effectiveTo: CHANGE,
      attribution: attribution('assertion:external:ca:provincial:old'),
    },
    {
      externalIdentifierId: 'external:ca:provincial:new',
      entityKind: 'district',
      entityId: did('district:ca:maple-provincial'),
      issuer: 'synthetic-ca-election-authority',
      identifier: 'MAPLE-PROV-NEW',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:external:ca:provincial:new'),
    },
    {
      externalIdentifierId: 'external:us:county-board',
      entityKind: 'public_body',
      entityId: bid('body:us:county-board'),
      issuer: 'synthetic-us-public-body-registry',
      identifier: 'EXAMPLE-COUNTY-BOARD',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:external:us:county-board'),
    },
    {
      externalIdentifierId: 'external:us:water-office',
      entityKind: 'office',
      entityId: oid('office:us:water-director'),
      issuer: 'synthetic-us-special-district-registry',
      identifier: 'WATER-DIRECTOR-01',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:external:us:water-office', { coverage: 'partial' }),
    },
  ],
  gaps: [
    {
      gapId: 'gap:us:water:boundary-review',
      entityKind: 'district',
      entityId: did('district:us:water'),
      code: 'BOUNDARY_REVIEW_REQUIRED',
      message:
        'Synthetic special-district boundary coverage is partial and not suitable for location resolution.',
      effectiveFrom: START,
      effectiveTo: null,
      attribution: attribution('assertion:gap:us:water:boundary-review', {
        freshness: 'unknown',
        coverage: 'gap',
        conflict: 'conflicting',
      }),
    },
    {
      gapId: 'gap:ca:new-bay:office',
      entityKind: 'jurisdiction',
      entityId: jid('jurisdiction:ca:new-bay'),
      code: 'OFFICE_COVERAGE_PENDING',
      message: 'Synthetic post-amalgamation office coverage is intentionally incomplete.',
      effectiveFrom: CHANGE,
      effectiveTo: null,
      attribution: attribution('assertion:gap:ca:new-bay:office', {
        coverage: 'gap',
        freshness: 'unknown',
      }),
    },
  ],
} satisfies JurisdictionRegistrySnapshot);
